/**
 * sync-abi.ts
 * Extracts ABIs from Hardhat artifacts and generates TypeScript ABI files.
 * Integrates with sync-deployments to auto-generate ABIs on deployment sync.
 *
 * Usage:
 *   bun run scripts/sync-abi.ts
 */

import fs from 'fs';
import path from 'path';

const REPO_ROOT = path.resolve(__dirname, '../../..');

// Contract name → TypeScript file name (kebab-case)
const CONTRACT_ABI_MAP: Record<string, string> = {
  'AIAgentRegistry': 'AIAgentRegistry',
  'AIAgentRuleManager': 'AIAgentRuleManager',
  'AttestationVerifier': 'AttestationVerifier',
  'CombinedRuleStorage': 'CombinedRuleStorage',
  'MockEAS': 'MockEAS',
  'MockOracle': 'MockOracle',
  'PayIDVerifier': 'PayIDVerifier',
  'PayWithPayID': 'PayWithPayID',
  'PayWithPayIDBatch': 'PayWithPayIDBatch',
  'RecurringPayments': 'RecurringPayments',
  'RuleAuthority': 'RuleAuthority',
  'RuleItemERC721': 'RuleItemERC721',
  'AgentPayID': 'AgentPayID',
  'MockAgentRegistry': 'MockAgentRegistry',
  'VindexRegistry': 'VindexRegistry',
  'EscrowMilestone': 'EscrowMilestone',
  'TimeLockVesting': 'TimeLockVesting',
};

// Source artifacts directory
const ARTIFACTS_DIR = path.join(REPO_ROOT, 'packages/contracts/artifacts/contracts');

// Target ABI files directory
const ABI_TARGET_DIR = path.join(REPO_ROOT, 'frontend/example-product/src/constants/contracts');

// Target index file
const INDEX_TARGET = path.join(ABI_TARGET_DIR, 'index.ts');

function findArtifact(contractName: string): string | null {
  // Search in core and test directories
  const searchDirs = ['core', 'test'];

  for (const dir of searchDirs) {
    const artifactPath = path.join(ARTIFACTS_DIR, dir, `${contractName}.sol`, `${contractName}.json`);
    if (fs.existsSync(artifactPath)) {
      return artifactPath;
    }
  }

  return null;
}

function generateAbiFile(contractName: string, abi: any[]): string {
  const tsName = CONTRACT_ABI_MAP[contractName];
  if (!tsName) {
    throw new Error(`No TypeScript name mapping for contract: ${contractName}`);
  }

  const abiName = `${tsName}Abi`;

  return (
    `// Auto-generated from ${contractName}.sol\n` +
    `export const ${abiName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

function updateIndexFile(existingExports: string[]): string {
  const header = `// Auto-generated by sync-deployments.ts — do not edit manually\n\n`;
  const imports = existingExports.map(exp => {
    const fileName = exp.replace('Abi', '');
    return `import { ${exp} } from './${fileName}';`;
  }).join('\n');
  const exports = existingExports.map(exp => `export { ${exp} };`).join('\n');

  return header + imports + '\n\n' + exports + '\n';
}

async function main() {
  console.log('\n🔍 Syncing contract ABIs...\n');

  const generatedFiles: string[] = [];
  const errors: string[] = [];

  for (const [contractName, tsName] of Object.entries(CONTRACT_ABI_MAP)) {
    try {
      const artifactPath = findArtifact(contractName);

      if (!artifactPath) {
        console.warn(`  ⚠️  Artifact not found: ${contractName}`);
        errors.push(`Artifact not found: ${contractName}`);
        continue;
      }

      console.log(`  📄 Processing: ${contractName}`);

      const artifactJson = JSON.parse(fs.readFileSync(artifactPath, 'utf-8'));
      const abi = artifactJson.abi;

      if (!abi || !Array.isArray(abi)) {
        console.warn(`  ⚠️  Invalid ABI in: ${contractName}`);
        errors.push(`Invalid ABI in: ${contractName}`);
        continue;
      }

      const abiContent = generateAbiFile(contractName, abi);
      const targetPath = path.join(ABI_TARGET_DIR, `${tsName}.ts`);

      fs.writeFileSync(targetPath, abiContent, 'utf-8');
      generatedFiles.push(`${tsName}Abi`);

      console.log(`  ✅ Generated: ${tsName}.ts`);
    } catch (error: any) {
      console.error(`  ❌ Error processing ${contractName}:`, error.message);
      errors.push(`${contractName}: ${error.message}`);
    }
  }

  // Update index.ts
  console.log('\n📝 Updating contracts/index.ts...');

  try {
    const abiExports = generatedFiles.sort();
    const indexContent = updateIndexFile(abiExports);
    fs.writeFileSync(INDEX_TARGET, indexContent, 'utf-8');
    console.log(`  ✅ Updated index.ts (${abiExports.length} exports)`);
  } catch (error: any) {
    console.error(`  ❌ Error updating index.ts:`, error.message);
    errors.push(`index.ts: ${error.message}`);
  }

  console.log(`\n✅ ABI sync complete (${generatedFiles.length} files generated)\n`);

  if (errors.length > 0) {
    console.log('\n⚠️  Errors encountered:');
    errors.forEach(err => console.log(`   - ${err}`));
    process.exit(1);
  }
}

main().catch((e: Error) => {
  console.error('❌ Fatal error:', e.message);
  process.exit(1);
});
