services:
  payid-example-product:
    build:
      context: ..
      dockerfile: frontend/example-product/Dockerfile
    container_name: payid-example-product
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - ./example-product/.env

  payid-frontend-docs:
    build:
      context: ..
      dockerfile: frontend/frontend-docs/Dockerfile
    container_name: payid-frontend-docs
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - ./frontend-docs/.env

networks:
  default:
    external: true
    name: nawasena-network