// Auto-generated by sync-deployments.ts — do not edit manually
// Last synced: 2026-05-16T10:59:09.256Z

export const addresses = {
  // Chain 16601
  16601: {
    AIAgentRegistry: "0x1D13fF25b10C9a6741DFdce229073bed652197c7" as `0x${string}`,
    AIAgentRuleManager: "0xB9d9e972100a1dD01cd441774b45b5821e136043" as `0x${string}`,
    AttestationVerifier: "0x24d41dbc3d60d0784f8a937c59FBDe51440D5140" as `0x${string}`,
    CombinedRuleStorage: "0xC976c932092ECcD8f328FfD85066C0c05ED54044" as `0x${string}`,
    MockEAS: "0x76cec9299B6Fa418dc71416FF353737AB7933A7D" as `0x${string}`,
    PayIDVerifier: "0xA3307BF348ACC4bEDdd67CCA2f7F0c4349d347Db" as `0x${string}`,
    PayWithPayID: "0x313F922BE1649cEc058EC0f076664500c78bdc0b" as `0x${string}`,
    RuleAuthority: "0x90c84237fDdf091b1E63f369AF122EB46000bc70" as `0x${string}`,
    RuleItemERC721: "0x3D63c50AD04DD5aE394CAB562b7691DD5de7CF6f" as `0x${string}`,
    AgentPayID: "0x707531c9999AaeF9232C8FEfBA31FBa4cB78d84a" as `0x${string}`,
    MockAgentRegistry: "0xa779C1D17bC5230c07afdC51376CAC1cb3Dd5314" as `0x${string}`,
    VindexRegistry: "0xBbc18b580256A82dC0F9A86152b8B22E7C1C8005" as `0x${string}`
  }
} as const;

export type SupportedChainId = keyof typeof addresses;
