// Auto-generated by sync-deployments.ts — do not edit manually
// Last synced: 2026-05-16T14:41:10.624Z

export const addresses = {
  // 0G Newton Testnet — Chain 16600
  16600: {
    AIAgentRegistry: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    AIAgentRuleManager: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    AttestationVerifier: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    CombinedRuleStorage: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    MockEAS: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    PayIDVerifier: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    PayWithPayID: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    RuleAuthority: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    RuleItemERC721: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    AgentPayID: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    MockAgentRegistry: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    VindexRegistry: "0x0000000000000000000000000000000000000000" as `0x${string}`
  },

  // 0G Newton Testnet (Fork) — Chain 16601
  16601: {
    AIAgentRegistry: "0x1eB5C49630E08e95Ba7f139BcF4B9BA171C9a8C7" as `0x${string}`,
    AIAgentRuleManager: "0x5A569Ad19272Afa97103fD4DbadF33B2FcbaA175" as `0x${string}`,
    AttestationVerifier: "0x6e0a5725dD4071e46356bD974E13F35DbF9ef367" as `0x${string}`,
    CombinedRuleStorage: "0xA9d0Fb5837f9c42c874e16da96094b14Af0e2784" as `0x${string}`,
    MockEAS: "0xa31F4c0eF2935Af25370D9AE275169CCd9793DA3" as `0x${string}`,
    PayIDVerifier: "0xF9c0bF1CFAAB883ADb95fed4cfD60133BffaB18a" as `0x${string}`,
    PayWithPayID: "0xb830887eE23d3f9Ed8c27dbF7DcFe63037765475" as `0x${string}`,
    RuleAuthority: "0x25A1DF485cFBb93117f12fc673D87D1cddEb845a" as `0x${string}`,
    RuleItemERC721: "0xD855cE0C298537ad5b5b96060Cf90e663696bbf6" as `0x${string}`,
    AgentPayID: "0x696358bBb1a743052E0E87BeD78AAd9d18f0e1F4" as `0x${string}`,
    MockAgentRegistry: "0x1f53E116c31F171e59f45f0752AEc5d1F5aA3714" as `0x${string}`,
    VindexRegistry: "0x22b1c5C2C9251622f7eFb76E356104E5aF0e996A" as `0x${string}`
  }
} as const;

export type SupportedChainId = keyof typeof addresses;
