// Auto-generated by sync-deployments.ts — do not edit manually
// Last synced: 2026-05-12T23:22:11.311Z

export const addresses = {
  // Localhost (Hardhat) — Chain 31337
  31337: {
    AttestationVerifier: "0xF85895D097B2C25946BB95C4d11E2F3c035F8f0C" as `0x${string}`,
    CombinedRuleStorage: "0x0b27a79cb9C0B38eE06Ca3d94DAA68e0Ed17F953" as `0x${string}`,
    MockEAS: "0x7bdd3b028C4796eF0EAf07d11394d0d9d8c24139" as `0x${string}`,
    MockEthUsdOracle: "0xB468647B04bF657C9ee2de65252037d781eABafD" as `0x${string}`,
    MockIDRX: "0x47c05BCCA7d57c87083EB4e586007530eE4539e9" as `0x${string}`,
    MockUSDC: "0x408F924BAEC71cC3968614Cb2c58E155A35e6890" as `0x${string}`,
    PayIDVerifier: "0x773330693cb7d5D233348E25809770A32483A940" as `0x${string}`,
    PayWithPayID: "0x52173b6ac069619c206b9A0e75609fC92860AB2A" as `0x${string}`,
    RuleAuthority: "0x40A633EeF249F21D95C8803b7144f19AAfeEF7ae" as `0x${string}`,
    RuleItemERC721: "0x532802f2F9E0e3EE9d5Ba70C35E1F43C0498772D" as `0x${string}`
  }
} as const;

export type SupportedChainId = keyof typeof addresses;
