// Auto-generated by sync-deployments.ts — do not edit manually
// Last synced: 2026-05-26T09:58:13.227Z
//
// To add a new chain: edit CHAIN_FULL_META in packages/contracts/scripts/sync-deployments.ts
// then run the sync command. This file will be regenerated automatically.

import type { Chain } from 'viem';

export const CHAIN_REGISTRY: Record<number, Chain> = {
  // 0G Newton Testnet
  16600: {
    id: 16600,
    name: '0G Newton Testnet',
    nativeCurrency: { decimals: 18, name: 'A0GI', symbol: 'A0GI' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_ZEROG_NEWTON_RPC_URL ?? 'https://16600.rpc.thirdweb.com'] },
      public: { http: [import.meta.env.VITE_ZEROG_NEWTON_RPC_URL ?? 'https://16600.rpc.thirdweb.com'] },
    },
    blockExplorers: {
      default: { name: '0G Explorer', url: 'https://chainscan-newton.0g.ai' },
    },
  },

  // 0G Newton Testnet (Fork)
  16601: {
    id: 16601,
    name: '0G Newton Testnet (Fork)',
    nativeCurrency: { decimals: 18, name: 'A0GI', symbol: 'A0GI' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_ZEROG_FORK_RPC_URL ?? 'http://100.73.196.95:8550'] },
      public: { http: [import.meta.env.VITE_ZEROG_FORK_RPC_URL ?? 'http://100.73.196.95:8550'] },
    },
    blockExplorers: {
      default: { name: '0G Explorer', url: 'https://chainscan-newton.0g.ai' },
    },
  },

  // 0G Galileo Testnet
  16602: {
    id: 16602,
    name: '0G Galileo Testnet',
    nativeCurrency: { decimals: 18, name: 'A0GI', symbol: 'A0GI' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_ZEROG_GALILEO_RPC_URL ?? 'https://evmrpc-testnet.0g.ai'] },
      public: { http: [import.meta.env.VITE_ZEROG_GALILEO_RPC_URL ?? 'https://evmrpc-testnet.0g.ai'] },
    },
    blockExplorers: {
      default: { name: '0G Galileo Explorer', url: 'https://chainscan-galileo.0g.ai' },
    },
  },

  // 0G Mainnet
  16661: {
    id: 16661,
    name: '0G Mainnet',
    nativeCurrency: { decimals: 18, name: '0G', symbol: '0G' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_ZEROG_MAINNET_RPC_URL ?? 'https://evmrpc.0g.ai'] },
      public: { http: [import.meta.env.VITE_ZEROG_MAINNET_RPC_URL ?? 'https://evmrpc.0g.ai'] },
    },
    blockExplorers: {
      default: { name: '0G Explorer', url: 'https://chainscan.0g.ai' },
    },
  },

  // DevNode
  31337: {
    id: 31337,
    name: 'DevNode',
    nativeCurrency: { decimals: 18, name: 'Dev Token', symbol: 'DEV' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_DEV_NODE_RPC_URL ?? '/rpc'] },
      public: { http: [import.meta.env.VITE_DEV_NODE_RPC_URL ?? '/rpc'] },
    },
  },

  // Local Fork
  31338: {
    id: 31338,
    name: 'Local Fork',
    nativeCurrency: { decimals: 18, name: 'ETH', symbol: 'ETH' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_LOCAL_FORK_RPC_URL ?? 'http://100.73.196.95:8550'] },
      public: { http: [import.meta.env.VITE_LOCAL_FORK_RPC_URL ?? 'http://100.73.196.95:8550'] },
    },
  },

  // Arbitrum Sepolia
  421614: {
    id: 421614,
    name: 'Arbitrum Sepolia',
    nativeCurrency: { decimals: 18, name: 'Ether', symbol: 'ETH' },
    rpcUrls: {
      default: { http: [import.meta.env.VITE_ARBITRUM_SEPOLIA_RPC_URL ?? 'https://sepolia-rollup.arbitrum.io/rpc'] },
      public: { http: [import.meta.env.VITE_ARBITRUM_SEPOLIA_RPC_URL ?? 'https://sepolia-rollup.arbitrum.io/rpc'] },
    },
    blockExplorers: {
      default: { name: 'Arbiscan Sepolia', url: 'https://sepolia.arbiscan.io' },
    },
  },
};
