// Auto-generated by sync-deployments.ts — do not edit manually

export const chainMeta = {
  137: { name: "polygon", label: "Polygon", isTestnet: false as const },
  1284: { name: "moonbeam", label: "Moonbeam", isTestnet: false as const },
  1285: { name: "moonriver", label: "Moonriver", isTestnet: false as const },
  1287: { name: "moonbaseAlpha", label: "Moonbase Alpha", isTestnet: true as const },
  4202: { name: "liskSepolia", label: "Lisk Sepolia", isTestnet: true as const },
  8453: { name: "base", label: "Base", isTestnet: false as const },
  10143: { name: "monadTestnet", label: "Monad Testnet", isTestnet: true as const },
  16601: { name: "zeroGTestnet", label: "0G Newton Testnet", isTestnet: true as const },
  31337: { name: "hardhat", label: "Localhost (Hardhat)", isLocal: true as const },
  80002: { name: "polygonAmoy", label: "Polygon Amoy", isTestnet: true as const },
  84532: { name: "baseSepolia", label: "Base Sepolia", isTestnet: true as const },
  11155111: { name: "sepolia", label: "Sepolia", isTestnet: true as const }
} as const;

export type ChainId = keyof typeof chainMeta;
