// Auto-generated by sync-deployments.ts — do not edit manually

export const chainMeta = {
  16600: { name: "zeroGTestnet", label: "0G Newton Testnet", isTestnet: true as const },
  16601: { name: "zeroGFork", label: "0G Newton Testnet (Fork)", isTestnet: true as const },
  16602: { name: "zeroGGalileo", label: "0G Galileo Testnet", isTestnet: true as const },
  16661: { name: "zeroGMainnet", label: "0G Mainnet", isTestnet: false as const },
  31337: { name: "devnode", label: "DevNode", isTestnet: true as const },
  31338: { name: "localFork", label: "Local Fork", isTestnet: true as const },
  421614: { name: "arbitrumSepolia", label: "Arbitrum Sepolia", isTestnet: true as const },
} as const;

export type ChainId = keyof typeof chainMeta;
