// Auto-generated by sync-deployments.ts — do not edit manually
export const combinedRuleStorageAbi = [
  {
    "inputs": [],
    "name": "ArrayLengthMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyRuleSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyRules",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidHash",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRuleNFTContract",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxRulesExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoActiveRule",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoActiveRuleForDirection",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRuleNFTOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RuleDeprecated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RuleExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RuleNFTAlreadyUsed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RuleNFTOwnershipSplit",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RuleNotActive",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      }
    ],
    "name": "CombinedRuleDeactivated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "CombinedRuleOwnershipSynced",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "CombinedRuleRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "enum CombinedRuleStorage.RuleDirection",
        "name": "direction",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "CombinedRuleRegisteredWithDirection",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_RULES",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "activeRuleOf",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "enum CombinedRuleStorage.RuleDirection",
        "name": "",
        "type": "uint8"
      }
    ],
    "name": "activeRuleOfByDirection",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "deactivateMyCombinedRule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "enum CombinedRuleStorage.RuleDirection",
        "name": "direction",
        "type": "uint8"
      }
    ],
    "name": "deactivateMyCombinedRuleForDirection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "getActiveRuleOf",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "enum CombinedRuleStorage.RuleDirection",
        "name": "direction",
        "type": "uint8"
      }
    ],
    "name": "getActiveRuleOfByDirection",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      }
    ],
    "name": "getRuleByHash",
    "outputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "ruleNFT",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          }
        ],
        "internalType": "struct CombinedRuleStorage.RuleRef[]",
        "name": "ruleRefs",
        "type": "tuple[]"
      },
      {
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      }
    ],
    "name": "isActive",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "listAllRuleSetHashes",
    "outputs": [
      {
        "internalType": "bytes32[]",
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      },
      {
        "internalType": "address[]",
        "name": "ruleNFTs",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "tokenIds",
        "type": "uint256[]"
      },
      {
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "registerCombinedRule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      },
      {
        "internalType": "enum CombinedRuleStorage.RuleDirection",
        "name": "direction",
        "type": "uint8"
      },
      {
        "internalType": "address[]",
        "name": "ruleNFTs",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "tokenIds",
        "type": "uint256[]"
      },
      {
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "registerCombinedRuleForDirection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ruleSetHash",
        "type": "bytes32"
      }
    ],
    "name": "syncOwner",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "usedRuleNFT",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
