// Auto-generated by sync-deployments.ts — do not edit manually
export const mockOracleAbi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "ethUsd",
    "outputs": [
      {
        "internalType": "contract MockV3Aggregator",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
