import React, { StrictMode } from 'react'
import ReactDOM from 'react-dom/client'
import {
  Outlet,
  RouterProvider,
  createRootRoute,
  createRoute,
  createRouter,
  useNavigate,
} from '@tanstack/react-router'
import { WagmiProvider, createConfig, http } from 'wagmi'
import { injected } from 'wagmi/connectors'
import { PayIDProvider } from 'payid-react'
import * as TanStackQueryProvider from './integrations/tanstack-query/root-provider.tsx'
import { CHAIN_REGISTRY } from './constants/contracts/chainRegistry'

// V4 hackathon futuristic UI — pages now live in features/
import {
  LandingPageV4,
  AppLayout as V4AppLayout,
  ThemeProvider as V4ThemeProvider,
} from './components/v4'
import { AdvancedTools as V4AdvancedTools } from '@/features/tools'
import { AdminPage as V4AdminPage } from '@/features/admin'
import { AgentPayIDPage as V4AgentPayIDPage, UserAIAgentsPage as V4UserAIAgentsPage } from '@/features/agent'
import { Dashboard as V4Dashboard } from '@/features/dashboard'
import { DAOPayroll as V4DAOPayroll } from '@/features/dao-payroll'
import { HistoryPage as V4HistoryPage } from '@/features/history'
import { PolicyMarketplace as V4PolicyMarketplace } from '@/features/marketplace'
import { ProofVisualizer as V4ProofVisualizer } from '@/features/proof-visualizer'
import { ReceivePage as V4ReceivePage } from '@/features/receive'
import { RulesPage as V4RulesPage, RulesConsolePage as V4RulesConsolePage } from '@/features/rules'
import { SendFlow as V4SendFlow } from '@/features/send'
import { SettingsPage as V4SettingsPage } from '@/features/settings'
import { CheckoutPage as V4CheckoutPage } from '@/features/checkout'
import { GiftCardPage as V4GiftCardPage, GiftClaimPage as V4GiftClaimPage } from '@/features/gift'
import { TimeLockVesting as V4TimeLockVesting } from '@/features/shared'
import { ReputationPage as V4ReputationPage, ScamReportPage as V4ScamReportPage } from '@/features/reputation'

import { addresses } from './constants/contracts/addresses'
import { Toaster } from './components/ui/sonner'
import './globals.css'
import reportWebVitals from './reportWebVitals.ts'

import type { Chain } from 'viem'

// CHAIN_REGISTRY is auto-generated by sync-deployments.ts.
// To add a new chain, edit CHAIN_FULL_META in packages/contracts/scripts/sync-deployments.ts
// then run the sync command — this file is not touched manually.

// Derive active chains from deployed addresses — wagmiConfig updates automatically on sync
const HIDDEN_CHAIN_IDS = new Set([16600, 16601]) // 0G Newton chains (not in use)
const deployedChainIds = Object.keys(addresses).map(Number)
const activeChains = deployedChainIds
  .filter(id => !HIDDEN_CHAIN_IDS.has(id))
  .map(id => CHAIN_REGISTRY[id])
  .filter((c): c is Chain => !!c)

// Wagmi requires at least one chain
const chainsForWagmi = (activeChains.length > 0 ? activeChains : [CHAIN_REGISTRY[16602]!]) as [Chain, ...Chain[]]

const wagmiConfig = createConfig({
  chains: chainsForWagmi,
  connectors: [injected({ shimDisconnect: true })],
  transports: Object.fromEntries(chainsForWagmi.map(c => [c.id, http()])),
})

// Re-export for components that import individual chain objects
export const zeroGTestnet = CHAIN_REGISTRY[16600]!
export const zeroGFork = CHAIN_REGISTRY[16601]!
export const zeroGGalileo = CHAIN_REGISTRY[16602]!
export const devNode = CHAIN_REGISTRY[31337]!
export const localFork = CHAIN_REGISTRY[31338]!

const rootRoute = createRootRoute({
  component: () => <Outlet />,
})

// Root index redirect to latest version (v4)
const rootIndexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => {
    const navigate = useNavigate()
    React.useEffect(() => {
      navigate({ to: '/v4' })
    }, [])
    return null
  },
})

// V4 hackathon futuristic routes
const v4Route = createRoute({
  getParentRoute: () => rootRoute,
  path: '/v4',
  component: () => (
    <V4ThemeProvider>
      <Outlet />
    </V4ThemeProvider>
  ),
})

const v4IndexRoute = createRoute({
  getParentRoute: () => v4Route,
  path: '/',
  component: LandingPageV4,
})

const v4AppRoute = createRoute({
  getParentRoute: () => v4Route,
  path: 'app',
  component: () => (
    <V4AppLayout>
      <Outlet />
    </V4AppLayout>
  ),
})

const v4AppIndexRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: '/',
  component: V4Dashboard,
})

const v4DashboardRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'dashboard',
  component: V4Dashboard,
})

const v4SendRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'send',
  component: V4SendFlow,
})

const v4ReceiveRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'receive',
  component: V4ReceivePage,
})

const v4GiftRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'gift',
  component: V4GiftCardPage,
})

const v4GiftClaimRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'gift/claim',
  component: V4GiftClaimPage,
})

const v4HistoryRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'history',
  component: V4HistoryPage,
})

const v4RulesRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'rules',
  component: V4RulesConsolePage,
})

const v4RulesBuilderRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'rules/builder',
  component: V4RulesPage,
})

const v4ProofRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'proof',
  component: V4ProofVisualizer,
})

const v4MarketplaceRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'marketplace',
  component: V4PolicyMarketplace,
})

const v4AdvancedToolsRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'tools',
  component: V4AdvancedTools,
})

const v4DAOPayrollRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'payroll',
  component: V4DAOPayroll,
})

const v4VestingRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'vesting',
  component: V4TimeLockVesting,
})

const v4SettingsRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'settings',
  component: V4SettingsPage,
})

const v4AdminRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'admin',
  component: V4AdminPage,
})

const v4AgentRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'agent',
  component: V4AgentPayIDPage,
})

const v4AIAgentMarketplaceRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'ai-agents',
  component: V4UserAIAgentsPage,
})

const v4CheckoutRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'checkout',
  component: V4CheckoutPage,
})

const v4ReputationRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'reputation',
  component: V4ReputationPage,
})

const v4ScamReportRoute = createRoute({
  getParentRoute: () => v4AppRoute,
  path: 'reputation/report',
  component: V4ScamReportPage,
})

const routeTree = rootRoute.addChildren([
  rootIndexRoute,
  v4Route.addChildren([
    v4IndexRoute,
    v4AppRoute.addChildren([
      v4AppIndexRoute,
      v4DashboardRoute,
      v4SendRoute,
      v4ReceiveRoute,
      v4GiftRoute,
      v4GiftClaimRoute,
      v4HistoryRoute,
      v4RulesRoute,
      v4RulesBuilderRoute,
      v4ProofRoute,
      v4MarketplaceRoute,
      v4AdvancedToolsRoute,
      v4DAOPayrollRoute,
      v4VestingRoute,
      v4SettingsRoute,
      v4AdminRoute,
      v4AgentRoute,
      v4AIAgentMarketplaceRoute,
      v4CheckoutRoute,
      v4ReputationRoute,
      v4ScamReportRoute,
    ]),
  ]),
])

const TanStackQueryProviderContext = TanStackQueryProvider.getContext()

const router = createRouter({
  routeTree,
  context: { ...TanStackQueryProviderContext },
  defaultPreload: 'intent',
  scrollRestoration: true,
  defaultStructuralSharing: true,
  defaultPreloadStaleTime: 0,
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

// Render
const rootElement = document.getElementById('app')

if (rootElement && !rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement)
  root.render(
    <StrictMode>
      <WagmiProvider config={wagmiConfig}>
        <TanStackQueryProvider.Provider {...TanStackQueryProviderContext}>
          <PayIDProvider
            contracts={Object.keys(addresses).reduce((acc, cid) => {
              const chainId = Number(cid)
              const addr = (addresses as any)[chainId]
              acc[chainId] = {
                ruleAuthority: addr.RuleAuthority,
                ruleItemERC721: addr.RuleItemERC721,
                payIDVerifier: addr.PayIDVerifier,
                payWithPayID: addr.PayWithPayID,
                combinedRuleStorage: addr.CombinedRuleStorage,
                vindexRegistry: addr.VindexRegistry,
                attestationVerifier: addr.AttestationVerifier,
                aiAgentRegistry: addr.AIAgentRegistry,
                aiAgentRuleManager: addr.AIAgentRuleManager,
              }
              return acc
            }, {} as any)}
            ipfsGateway={(import.meta.env.VITE_PINATA_GATEWAY as string | undefined) ?? 'https://gateway.pinata.cloud/ipfs/'}
            zgGateway={(import.meta.env.VITE_0G_STORAGE_GATEWAY as string | undefined) ?? 'https://indexer-storage-testnet-turbo.0g.ai'}
          >
            <RouterProvider router={router} />
            <Toaster position="bottom-right" richColors />
          </PayIDProvider>
        </TanStackQueryProvider.Provider>
      </WagmiProvider>
    </StrictMode>,
  )
}

reportWebVitals()
