name: Deploy PayID Frontends

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, nawasena, production]

    steps:
      - name: Deploy PayID Frontends
        run: |
          cd ~/apps/payId-sdk
          git pull
          docker compose -f frontend/docker-compose.yml down
          docker compose -f frontend/docker-compose.yml up -d --build